### ISSUE TITLE
Play OS X and iOS no longer passes token follow upgrade

### ISSUE THREAD

**Issue by benbalter** [play/play-cocoa#23]
Since the Play server was updated, neither the OS X app nor the iOS app can properly authenticate with the it (first time).

Add the URL, add my token, and on OS X I get the error:

```
{NSLocalizedDescription=Expected content type {(
        "text/javascript",
        "application/json",
        "text/json"
    )}, got text/html, NSErrorFailingURLKey=http://[domain]/streaming_info}
```

Going to `/streaming_info` in a non-authenticated browser redirects me to GitHub's Oauth flow. `/streaming_info?token=[token]` properly returns the stream URL.

Halp?

cc @maddox

**Comment by holman** [comment]
This may be because I had to add the `json` gem because of dependencies. Dunno though.

**Comment by benbalter** [comment]
Closing the issue. This isn't the issue you're looking for. This never happend. Sorry for the hassle.
